[project]
name = "ml-infr-ops"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "sagemaker>2.240.0",
    "boto3>1.38.00",
    "awswrangler>3.0.0",
    "pandas>2.0.0",
    "redshift-connector",
    "pendulum",
    "python-decouple",
    "cachetools",
    "tqdm",
    "redis[hiredis]>=4.5",
    "notebook",
    "pyspark",
    "feast[redis, spark, duckdb]==0.51.0"
]


[tool.ruff]
line-length = 120
target-version = "py311"
# Exclude common directories (defaults include many, but you can customize as needed)
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  ".venv",
  "infra",
  "mlops",
  "tofu",
  "demo_project",
  "jenkins"
]

[tool.ruff.lint]
select = [
  "E4", "E7", "E9", "F",   # core pyflakes + pycodestyle
  "B",                     # flake8-bugbear
  "I",                     # import sorting (isort-like rules)
  "ISC",                   # implicit string concatenation across lines
  "UP"                     # pyupgrade-style modernizations
]
ignore = [
  "E501",  # formatting line-length handled by the formatter
  "F403", "F405"  # suppress warnings about 'import *'
]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = ["S101"]  # e.g., allow assert statements in test code

[tool.ruff.format]
quote-style = "double"            # enforce double quotes (Black-compatible)
indent-style = "space"            # spaces (not tabs)
docstring-code-format = true      # reformat Python code in docstrings
docstring-code-line-length = "dynamic"  # docstring snippets respect global line-length