apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
  namespace: feast
stringData:
  redis: |
    type: redis
    connection_string: redis-service.feast.svc.cluster.local:6379
  sql: |
    path: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-service.feast.svc.cluster.local:5432/${POSTGRES_DB}
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: example
  namespace: feast
spec:
  feastProject: devour
  feastProjectDir:
    git:
      url: https://github.com/ShumzZzZz/devour
      ref: 6f6510e
      featureRepoPath: devour_feature_store # demo_project/staging/feature_repo
  services:
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
        server:
          envFrom:
          - secretRef:
              name: feast-secret
          - configMapRef:
              name: feast-config
          logLevel: debug
    offlineStore:
      persistence:
        file:
          type: duckdb
    onlineStore:
      persistence:
        store:
          type: redis
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
        - secretRef:
            name: feast-secret
        - configMapRef:
            name: feast-config
        env:
        - name: MPLCONFIGDIR
          value: /tmp
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
        logLevel: debug
    ui:
      envFrom:
      - secretRef:
          name: feast-secret
      - configMapRef:
          name: feast-config
      logLevel: debug

