apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-pod-scheduling
  namespace: kyverno
spec:
  # 1) Deployment, DaemonSet, StatefulSet, Job
  rules:
    - name: inject-scheduling-deployments-daemonsets-statefulsets-jobs
      match:
        any:
          - resources:
              kinds: [Deployment, DaemonSet, StatefulSet, Job]
              namespaces: [feast, feast-operator-system, istio-system, kubernetes-dashboard, feast-spark, kube-system, monitoring, airflow]
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                nodeSelector:
                  dedicated: featurestore
                tolerations:
                  - key: dedicated
                    operator: "Equal"
                    value: featurestore
                    effect: "NoExecute"

    # 2) Pod
    - name: inject-scheduling-pods
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [feast, feast-operator-system, istio-system, kubernetes-dashboard, feast-spark, kube-system, monitoring, airflow]
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              dedicated: featurestore
            tolerations:
              - key: dedicated
                operator: "Equal"
                value: featurestore
                effect: "NoExecute"

    # 3) CronJob
    - name: inject-scheduling-cronjobs
      match:
        any:
          - resources:
              kinds: [CronJob]
              namespaces: [feast, feast-operator-system, istio-system, kubernetes-dashboard, feast-spark, kube-system, monitoring, airflow]
      mutate:
        patchStrategicMerge:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    nodeSelector:
                      dedicated: featurestore
                    tolerations:
                      - key: dedicated
                        operator: "Equal"
                        value: featurestore
                        effect: "NoExecute"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: feast-pod-set-workingdir
  namespace: kyverno
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: feast-override-workingdir
      match:
        any:
          - resources:
              kinds: ["Deployment"]
              namespaces: "feast"
              selector:
                matchExpressions:
                  - key: "feast.dev/name"
                    operator: Exists
      mutate:
        foreach:
          - list: "request.object.spec.template.spec.containers"
            patchStrategicMerge:
              spec:
                template:
                  spec:
                    containers:
                      - name: "{{ element.name }}"
                        workingDir: "/feast-data-original/devour/"